### ISSUE TITLE
Allow creating Super Zips that run on Windows.

### ISSUE THREAD

**Issue by itsjohncs** [itsjohncs/superzippy#27]
I have a dual booted Windows 8 machine I can test Superzippy on. I'm not sure if it's worth   actually supporting Windows, but I'd be interested to know how difficult it would be. I can set up a VM to run tests if I do decide to support Windows.

**Comment by krisztianfekete** [comment]
I have not used superzippy before, but I will need to distribute tools to all of the major platforms (Windows/Mac/Linux) and just experimented with zipping up the code and prefixing it with shell commands - as superzippy does, so I thought to share how I think it could be done.

For windows support I see two options:

Windows can directly execute files with `.cmd` extensions if they contain meaningful batch commands.
So the code before the zip is different for Windows - it is something like (use `CRLF` as end of line!!!)

```batch
@echo off
python.exe "%~f0" %*
exit /b %errorlevel%
```

for explanation of the magic characters see http://ss64.com/nt/syntax-args.html

This feature would need something like
- `--windows` switch
- `.cmd` extension when `--windows` is specified
- Windows specific code before the zipped content

----

Another option is to provide a `.cmd` file that registers the `.sz` extension as `Python.File` and let python run `Python.Files`, also making `.sz` a known executable extension.  Running this `.cmd` file once will enable use of `.sz` files created for linux/macosx.

This needs changing some settings permanently
- [`FTYPE` & `ASSOC`](http://ss64.com/nt/ftype.html)
- [`PATHEXT`](http://www.voidspace.org.uk/python/articles/command_line.shtml#pathext) variable (from windows 7 there is a [`setx`](http://ss64.com/nt/setx.html) command to do this)

**Comment by brownhead** [comment]
The `.cmd` trick sounds good to me. It's straightforward, portable, and doesn't require an installation step besides having Python around. These are all attributes of super zips on non-Windows platforms too, so it would be good to keep them consistent.

Thank you for investigating this! I'm not sure when I'd be able to implement this, but if you or anyone else wants to implement it I'd be excited to bring it in.

**Comment by brownhead** [comment]
Creating a simple bootstrapping program that just runs Python on itself also seems easy to do, and that could be a `.exe` file. I'd like cross-compiling to be dirt-easy, which seems like it might be at least a little tricky. But probably not too bad.
