### ISSUE TITLE
Create landing page for tool.

### ISSUE THREAD

**Issue by itsjohncs** [itsjohncs/superzippy#29]
I think the selling point with this tool is its extreme simplicity. There's some great other options out there, but with their awesome and plentiful feature set they've made compromises in terms of usability and complexity.

I think I can probably show how easy superzippy is to use in two lines of text, and can show exactly how it works with a few more.

**Comment by brownhead** [comment]
Some folks have a lot of love for PyInstaller. The only selling point for superzippy is the simplicity of the whole thing (you can understand exactly what Superzippy does and create some intuition for when and where it'll work in like 15 minutes), and I should make that clear.

If I can make superzippy dirt easy to use, I think it'd be a good competitor. Soaking up the tiny niche market of "I want to ship a single executable for this small Python script I made but I'm tired of forcing all my code into one script, grumble grumble grumble", which was me when I made this.
